-- Question 1
SET DEFINE ON;
SET SERVEROUTPUT ON;
ACCEPT  FNAME CHAR PROMPT 'Enter YOUR FIRST NAME : ';
ACCEPT LNAME CHAR PROMPT 'Enter YOUR LAST NAME : ';
DECLARE
v_fname VARCHAR(50);
v_lname VARCHAR(50);
BEGIN
v_fname := '&FNAME';
v_lname := '&LNAME';
DBMS_OUTPUT.PUT_LINE('THE FIRST NAME IS  ' || v_fname);
DBMS_OUTPUT.PUT_LINE('THE LAST NAME IS ' || v_lname);
END;

-- Question 2

SET SERVEROUTPUT ON;
DECLARE
nbr1 number;
BEGIN
SELECT COUNT(*) INTO nbr1 FROM Employees;
DBMS_OUTPUT.PUT_LINE('NUMBER OF EMPLOYEES IS  ' || nbr1);
END;

-- Question 3

SET SERVEROUTPUT ON;
DECLARE
nbr2 number;
BEGIN
SELECT COUNT(*) INTO nbr2 FROM Employees WHERE MANAGER_ID=1;
DBMS_OUTPUT.PUT_LINE('NUMBER OF EMPLOYEES HAVING A MANAGER WITH ID = 1 IS :  ' || nbr2);
END;

-- Question 4
DECLARE
nbr1 number;
nbr2 number;
prop number;
BEGIN
SELECT COUNT(*) INTO nbr1 FROM Employees;
SELECT COUNT(*) INTO nbr2 FROM Employees WHERE MANAGER_ID=1;
prop:=(nbr2/nbr1)*100;
DBMS_OUTPUT.PUT_LINE('THE PROPORTION IS :  ' || prop);
END;

-- Question 5

SET DEFINE ON;
SET SERVEROUTPUT ON; 
ACCEPT id CHAR PROMPT 'Enter THE ID : ';
DECLARE
v_id VARCHAR(30);
v_last_name EMPLOYEES.LAST_NAME%TYPE;
v_first_name EMPLOYEES.FIRST_NAME%TYPE;
v_hire_date EMPLOYEES.HIRE_DATE%TYPE;
v_verify NUMBER;
BEGIN
v_id := '&id';
SELECT COUNT(*) INTO v_verify FROM EMPLOYEES WHERE EMPLOYEE_ID=v_id;
IF v_verify=0 THEN
DBMS_OUTPUT.PUT_LINE('USER NOT FOUND !');
ELSE
SELECT LAST_NAME, FIRST_NAME, HIRE_DATE INTO v_last_name, v_first_name, v_hire_date  FROM EMPLOYEES WHERE EMPLOYEE_ID=v_id;
DBMS_OUTPUT.PUT_LINE('The first name is  ' || v_first_name);
DBMS_OUTPUT.PUT_LINE('The last name is  ' || v_last_name);
DBMS_OUTPUT.PUT_LINE('The hire date is  ' || v_hire_date);
END IF;
END;


-- Question 6


SET DEFINE ON;
SET SERVEROUTPUT ON;
ACCEPT id CHAR PROMPT 'Enter THE ID : ';
DECLARE
v_id VARCHAR(30);
v_user EMPLOYEES%ROWTYPE;
v_verify NUMBER;
BEGIN
v_id := '&id';
SELECT COUNT(*) INTO v_verify FROM EMPLOYEES WHERE EMPLOYEE_ID=v_id;
IF v_verify=0 THEN
DBMS_OUTPUT.PUT_LINE('USER NOT FOUND !');
ELSE
SELECT * INTO v_user FROM EMPLOYEES WHERE EMPLOYEE_ID=v_id;
DBMS_OUTPUT.PUT_LINE('The first name is  ' || v_user.FIRST_NAME);
DBMS_OUTPUT.PUT_LINE('The last name is  ' || v_user.LAST_NAME);
DBMS_OUTPUT.PUT_LINE('The hire date is  ' || v_user.HIRE_DATE);
END IF;
END;

-- Question 7

SET DEFINE ON;
SET SERVEROUTPUT ON;
ACCEPT id CHAR PROMPT 'Entrer l''ID : ';
DECLARE
v_id VARCHAR(30);
v_product PRODUCTS%ROWTYPE;
v_verify NUMBER;
v_categ PRODUCT_CATEGORIES.CATEGORY_NAME%TYPE;
BEGIN
v_id := '&id';
SELECT COUNT(*) INTO v_verify FROM PRODUCTS WHERE PRODUCT_ID=v_id;
IF v_verify=0 THEN
DBMS_OUTPUT.PUT_LINE('PRODUCT NOT FOUND !');
ELSE
SELECT * INTO v_product FROM PRODUCTS WHERE PRODUCT_ID=v_id;
SELECT CATEGORY_NAME INTO v_categ FROM PRODUCT_CATEGORIES WHERE CATEGORY_ID=v_product.CATEGORY_ID;
DBMS_OUTPUT.PUT_LINE('PRODUCT NAME :  ' || v_product.PRODUCT_NAME);
DBMS_OUTPUT.PUT_LINE('DESCRIPTION :  ' || v_product.DESCRIPTION);
DBMS_OUTPUT.PUT_LINE('STANDARD COST  ' || v_product.STANDARD_COST);
DBMS_OUTPUT.PUT_LINE('LIST PRICE :  ' || v_product.LIST_PRICE);
DBMS_OUTPUT.PUT_LINE('PRODUCT CATEGORY :  ' || v_categ);
END IF;
END;

-- Question 8

SET DEFINE ON;
SET SERVEROUTPUT ON;
ACCEPT id CHAR PROMPT 'Entrer l''ID : ';
DECLARE
v_id VARCHAR(30);
r_mgr EMPLOYEES%ROWTYPE;
r_emp EMPLOYEES%ROWTYPE;
v_verify NUMBER;
BEGIN
v_id := '&id';
SELECT COUNT(*) INTO v_verify FROM EMPLOYEES WHERE EMPLOYEE_ID=v_id;
IF v_verify=0 THEN
DBMS_OUTPUT.PUT_LINE('EMPLOYEE NOT FOUND  !');
ELSE
SELECT * INTO r_emp FROM EMPLOYEES WHERE EMPLOYEE_ID=v_id;
SELECT * INTO r_mgr FROM EMPLOYEES WHERE EMPLOYEE_ID=r_emp.MANAGER_ID;
DBMS_OUTPUT.PUT_LINE('---EMPLOYEE INFORMATION---');
DBMS_OUTPUT.PUT_LINE('FIRST NAME :  ' || r_emp.FIRST_NAME);
DBMS_OUTPUT.PUT_LINE('LAST NAME :  ' || r_emp.LAST_NAME);
DBMS_OUTPUT.PUT_LINE('EMAIL : ' || r_emp.EMAIL);
DBMS_OUTPUT.PUT_LINE('PHONE :  ' || r_emp.PHONE);
DBMS_OUTPUT.PUT_LINE('HIRE DATE :  ' || r_emp.HIRE_DATE);
DBMS_OUTPUT.PUT_LINE('JOB TITLE :  ' || r_emp.JOB_TITLE);
DBMS_OUTPUT.PUT_LINE('---EMPLOYEE''S MANAGER INFORMATION---');
DBMS_OUTPUT.PUT_LINE('FIRST NAME :  ' || r_mgr.FIRST_NAME);
DBMS_OUTPUT.PUT_LINE('LAST NAME :  ' || r_mgr.LAST_NAME);
DBMS_OUTPUT.PUT_LINE('EMAIL : ' || r_mgr.EMAIL);
DBMS_OUTPUT.PUT_LINE('PHONE :  ' || r_mgr.PHONE);
DBMS_OUTPUT.PUT_LINE('HIRE DATE :  ' || r_mgr.HIRE_DATE);
DBMS_OUTPUT.PUT_LINE('JOB_TITLE :  ' || r_mgr.JOB_TITLE);

END IF;
END;

-- Question 9

SET DEFINE ON;
SET SERVEROUTPUT ON;
ACCEPT id CHAR PROMPT 'Entrer l''ID : ';
DECLARE
TYPE order_list IS TABLE OF ORDERS%ROWTYPE;
v_orders order_list := order_list();
v_name CUSTOMERS.NAME%TYPE; 
v_id VARCHAR(30);
v_verify1 NUMBER;
v_verify2 NUMBER;
BEGIN
v_id := '&id';
SELECT COUNT(*) INTO v_verify1 FROM CUSTOMERS WHERE CUSTOMER_ID=v_id;
IF v_verify1=0 THEN
DBMS_OUTPUT.PUT_LINE('CUSTOMER NOT FOUND !');
ELSE
SELECT COUNT(*) INTO v_verify2 FROM ORDERS WHERE CUSTOMER_ID=v_id;
IF v_verify2=0 THEN
DBMS_OUTPUT.PUT_LINE('THERE IS NO ORDER FOR THIS CUSTOMER !'); 
ELSE
SELECT NAME INTO v_name FROM CUSTOMERS WHERE CUSTOMER_ID='&id';
SELECT * BULK COLLECT INTO v_orders FROM ORDERS WHERE CUSTOMER_ID=v_id;
DBMS_OUTPUT.PUT_LINE('******** ORDERS BY THE CUSTOMER : ' || v_name || ' ARE********' );    
DBMS_OUTPUT.PUT_LINE('ORDER ID          STATUS           ORDER DATE           SALESMAN ID');  
FOR i IN v_orders.FIRST .. v_orders.LAST LOOP      
DBMS_OUTPUT.PUT_LINE(v_orders(i).ORDER_ID || '               ' || v_orders(i).STATUS || '           ' || v_orders(i).ORDER_DATE|| '            ' || v_orders(i).SALESMAN_ID);
END LOOP;
END IF;
END IF;
END;


